name: Build Docker Image from Code
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: testing-env
    env:
      DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      OAUTH_SECRET_KEY: ${{ secrets.OAUTH_SECRET_KEY}}
      OAUTH_ALGORITHM: ${{ secrets.OAUTH_ALGORITHM }}
      OAUTH_EXPIRY_MINUTES: ${{ secrets.OAUTH_EXPIRY_MINUTES }}

    services:
      postgres:
        image: postgres:alpine3.19
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Pull Git repo
        uses: actions/checkout@v4
      - name: Install Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install Pytest
        run: pip install pytest
      - name: Run all tests
        run:
          pytest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: False
          tags: social-media-backend:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}